GET http://localhost:3000/api/user/1709377116960
###
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "favorites": []
}

###
PUT http://localhost:3000/api/user/1709377116960
Content-Type: application/json

{
  "email": "john.do1@example.com",
  "favorites": []
}

###
DELETE http://localhost:3000/api/user/1
###
POST http://localhost:3000/api/user/1/favorites/save
Content-Type: application/json

{
  "title": "Example",
  "description": "Example description",
  "link": "https://example.com/",
  "thumbnailUrl": "https://example.com/thumb.jpg",
  "thumbnailWidth": 123,
  "thumbnailHeight": 456,
  "imageUrl": "https://example.com/image.jpg"
}
###
GET http://localhost:3000/api/search/hawaii
###